default: true
# MD013/line-length - Breaks for HTML blocks
MD013: false
# MD033/no-inline-html - Allow inline HTML
MD033: false
# MD036 no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false
