default: true

# MD013/line-length - Line length
MD013:
  line_length: 80
  heading_line_length: 80
  code_block_line_length: 120
  tables: false
  code_blocks: true

# MD033/no-inline-html - Allow inline HTML
MD033: false

# MD036 no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false
